### ISSUE TITLE
Documentation link for stable is broken

### ISSUE THREAD

**Issue by yebai** [JuliaGaussianProcesses/AbstractGPs.jl#31] opened 2020-07-27 12:35 UTC
It seems the following link in README is currently broken

https://juliagaussianprocesses.github.io/AbstractGPs.jl/stable

However, the link for the dev version works fine. Any idea why?

**Comment by theogf** [comment] 2020-07-27 12:52
It's not broken, it's just no release has been made since the first docs commit :)

**Comment by yebai** [comment] 2020-07-27 13:09
Ah, I see, thanks for the clarification. Shall we make a new release then?

**Comment by sharanry** [comment] 2020-07-27 13:18
I have bumped the version. Commit: [f608fa1](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/commit/4a73c78744617379b06e991fbc78d32f3f608fa1)

**Comment by sharanry** [comment] 2020-07-27 13:44
> I have bumped the version and tagged a release. Commit: [f608fa1](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/commit/4a73c78744617379b06e991fbc78d32f3f608fa1)

Looks like a patch release won't do. It needs to be at least a minor release. Should I create a minor release?

**Comment by willtebbutt** [comment] 2020-07-27 13:51
Nah. Just remove the stable option for now - the dev docs are completely fine.

To be honest it's really unclear that we ever want people to look at the "stable" docs -- we do continuous delivery and require the docs to successfully build before releasing a new version. As such, any version bump should be considered a stable release.

**Comment by sharanry** [comment] 2020-07-27 14:02
Yeah using "dev" has the default branch seems like a wonderful idea. However, currently https://juliagaussianprocesses.github.io/AbstractGPs.jl points to nowhere. I am not sure how to make this point to "dev".

**Comment by willtebbutt** [comment] 2020-07-27 14:10
> However, currently https://juliagaussianprocesses.github.io/AbstractGPs.jl points to nowhere.

Perhaps I'm confused -- possibly I'm missing something important. Is it not sufficient to just remove the docs-stable badge from the `AbstractGPs` readme and just assume that users will click the dev one?

**Comment by theogf** [comment] 2020-07-27 14:15
I think what @sharanry proposes is remove the notion of dev/stable and forward everything to the website hosted on  https://juliagaussianprocesses.github.io/AbstractGPs.jl

**Comment by sharanry** [comment] 2020-07-27 14:21
I suggest we remove the notion of "stable" and make "dev" (which points to the master's docs) the default. We could also keep tagged minor/patch release version. 

PS. I figured out a way to deploy docs for patch releases.

**Comment by willtebbutt** [comment] 2020-07-27 14:27
Ohhhh I see, fine. Well then I suppose that there are two solutions:

1. Figure out how to make everything point towards https://juliagaussianprocesses.github.io/AbstractGPs.jl
2. Just re-direct everything to https://juliagaussianprocesses.github.io/AbstractGPs.jl/dev

I don't have a strong preference either way, although the first one feels more like the "right" thing to do.

**Comment by theogf** [comment] 2020-07-27 14:42
I think the solution to 1. is to play with the `versions` keyword in `deploydocs` : https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs

**Comment by sharanry** [comment] 2020-07-27 14:47
> I think the solution to 1. is to play with the `versions` keyword in `deploydocs` : https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs

Yup. Working on it.

**Comment by yebai** [comment] 2020-07-27 14:51
FYI Julia documenter produces a versioned doc for every release, not just `stabe` or `dev`, see, e.g.:

https://juliagaussianprocesses.github.io/AbstractGPs.jl/v0.2/

It might be helpful to be able to look at older versions of the doc occasionally for reference.

**Comment by willtebbutt** [comment] 2020-07-27 15:15
I did not realise that was a thing, but I guess it makes sense. We definitely don't want to get rid of the versioned entries. Probably we just want to re-direct people from wherever they land to the docs for the most recent patch version.

**Comment by sharanry** [comment] 2020-07-27 15:48
> FYI Julia documenter produces a versioned doc for every release, not just `stabe` or `dev`, see, e.g.:
> 
> https://juliagaussianprocesses.github.io/AbstractGPs.jl/v0.2/
> 
> It might be helpful to be able to look at older versions of the doc occasionally for reference.

There is an option to produce tagged docs for every patch release instead of just minor release. Should I enable it? I am worried that it might become too cluttered.

**Comment by willtebbutt** [comment] 2020-07-27 15:50
I'm pro- enabling it. We can always disable it if it becomes problematic :)

**Comment by sharanry** [comment] 2020-07-27 21:31
I think the docs work as intended now. 😃  https://juliagaussianprocesses.github.io/AbstractGPs.jl

**Comment by sharanry** [comment] 2020-07-28 14:40
I think this issue is resolved. Closing this.

**Closed by sharanry** 2020-07-28 14:40 UTC

**Comment by yebai** [comment] 2020-07-28 15:01
Thanks, @sharanry!
