### ISSUE TITLE
Plotting PosteriorGPs seems to be broken in latest release

### ISSUE THREAD

**Issue by thomasgudjonwright** [JuliaGaussianProcesses/AbstractGPs.jl#152] opened 2021-05-26 13:51 UTC
The plot at the end of the documentation example [here](https://juliagaussianprocesses.github.io/AbstractGPs.jl/v0.2/examples/EllipticalSliceSampling/#Approximate-Inference-using-ESS) errors in the current release. These docs are from v0.2, but if v0.3 docs are not available, there should be a note added if the functionality is different (unless this is just a bug, in which case it should be fixed). I have confirmed that it works in v0.2.25 and is broken in v0.3.4 but have not check the versions in between.

I have mentioned this to @willtebbutt .

Here is the stacktrace and the call that produces it (context of call can be found in hyperlink above as it is directly copied)

`plot!(plt, p_fx, 0:0.001:1; label="Posterior")`

```
Cannot convert AbstractGPs.PosteriorGP{GP{AbstractGPs.ZeroMean{Float64}, Matern52Kernel{Distances.Euclidean}}, NamedTuple{(:α, :C, :x, :δ), Tuple{Vector{Float64}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, Vector{Float64}, Vector{Float64}}}} to series data for plotting

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] _prepare_series_data(x::AbstractGPs.PosteriorGP{GP{AbstractGPs.ZeroMean{Float64}, Matern52Kernel{Distances.Euclidean}}, NamedTuple{(:α, :C, :x, :δ), Tuple{Vector{Float64}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, Vector{Float64}, Vector{Float64}}}})
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/CirY4/src/series.jl:8
  [3] _series_data_vector(x::AbstractGPs.PosteriorGP{GP{AbstractGPs.ZeroMean{Float64}, Matern52Kernel{Distances.Euclidean}}, NamedTuple{(:α, :C, :x, :δ), Tuple{Vector{Float64}, LinearAlgebra.Cholesky{Float64, Matrix{Float64}}, Vector{Float64}, Vector{Float64}}}}, plotattributes::Dict{Symbol, Any})
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/CirY4/src/series.jl:27
  [4] macro expansion
    @ ~/.julia/packages/RecipesPipeline/CirY4/src/series.jl:143 [inlined]
  [5] apply_recipe(plotattributes::AbstractDict{Symbol, Any}, #unused#::Type{RecipesPipeline.SliceIt}, x::Any, y::Any, z::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:282
  [6] _process_userrecipes!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/CirY4/src/user_recipe.jl:36
  [7] recipe_pipeline!(plt::Any, plotattributes::Any, args::Any)
    @ RecipesPipeline ~/.julia/packages/RecipesPipeline/CirY4/src/RecipesPipeline.jl:70
  [8] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
    @ Plots ~/.julia/packages/Plots/iYDwd/src/plot.jl:172
  [9] plot!(::Plots.Plot, ::Any, ::Vararg{Any, N} where N; kw::Any)
    @ Plots ~/.julia/packages/Plots/iYDwd/src/plot.jl:162
 [10] top-level scope
    @ In[9]:3
 [11] eval
    @ ./boot.jl:360 [inlined]
 [12] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1094

```

**Comment by willtebbutt** [comment] 2021-05-26 13:58
Thanks for finding this and opening an issue.

It looks like the arguments are just the wrong way around in the docs.

Could you confirm that this fixes it:
```julia
plot!(plt, 0:0.001:1, p_fx; label="Posterior")
```
If so, would you mind opening a PR to this effect?

**Comment by devmotion** [comment] 2021-05-26 13:58
One of the breaking changes in v0.3 was that the plotting commands were changed: https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/121 and https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/131 We even added deprecation warnings, maybe they were incorrect or insufficient?

Also the examples were merged into one larger example which is available on 0.3: https://juliagaussianprocesses.github.io/AbstractGPs.jl/v0.3/examples/regression_1d/

As shown there, with 0.3 you should use
```julia

**Comment by willtebbutt** [comment] 2021-05-26 14:05
Oh. So the question is then @thomasgudjonwright how did you find this old version of the docs? We should make it so that people can't find them 😂

**Comment by thomasgudjonwright** [comment] 2021-05-26 15:30
Apologies then for this confusion. After the dev version, the first link that appeared was the v0.2 docs when searching AbstractGPs.jl, my bad!

**Comment by willtebbutt** [comment] 2021-05-26 15:31
@devmotion @theogf do we maybe want to make the v0.2 docs harder to discover or something?

**Comment by willtebbutt** [comment] 2021-05-26 15:45
Would it be straightforward to add a banner to all of the old docs that says "warning, these are old docs" or something? Not sure how straightforward that would be...

**Comment by devmotion** [comment] 2021-05-26 15:48
IIRC we did something similar in SciML a while ago: https://diffeq.sciml.ai/v5.3/

**Comment by devmotion** [comment] 2021-05-26 15:51
Here's the code for it: https://github.com/SciML/DiffEqDocs.jl/pull/447#issuecomment-792850075

**Comment by willtebbutt** [comment] 2021-05-26 15:52
This would be perfect to my mind.

**Comment by devmotion** [comment] 2021-05-26 15:57
It would be even better if Documenter would include such a functionality...

**Comment by devmotion** [comment] 2021-05-26 17:09
https://github.com/JuliaDocs/Documenter.jl/issues/1449

**Comment by devmotion** [comment] 2021-05-26 18:29
Should be fixed by https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/pull/153.

**Closed by devmotion** 2021-05-26 18:29 UTC
